#ANO 2025

In [ ]:
import pandas as pd

# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('tx_rend_escolas_2025.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

KeyboardInterrupt:

In [ ]:
df.info()

In [ ]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final.head(10))

In [ ]:
df_final.to_csv('Rendimento2025ano.csv', index=False)

#ANO 2024

In [ ]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('tx_rend_escolas_2024.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

In [ ]:
df.info()

In [ ]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final.head(10))

In [ ]:
df_final.to_csv('Rendimento2024ano.csv', index=False)

#ANO 2023

In [ ]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('tx_rend_escolas_2023.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

In [ ]:
df.info()

In [ ]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

In [ ]:
df_final.to_csv('Rendimento2023ano.csv', index=False)

#ANO 2022

In [ ]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('tx_rend_escolas_2022.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Nome do Município","Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Nome da Escola"
84887,Maricá,CEM JOANA BENEDICTA RANGEL
84888,Maricá,CE ELISIARIO MATTA
84889,Maricá,ESCOLA MUNICIPALIZADA BARRA DE ZACARIAS
84890,Maricá,E M BENVINDO TAQUES HORTA
84891,Maricá,CE DOMICIO DA GAMA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129311 entries, 7 to 129317
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                              Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                              --------------   -----
 0   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Ano                                                    129309 non-null  object
 1   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Região                                                 129308 non-null  object
 2   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - UF                                                     129308 non-null  object
 3   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Código do Município                                    129308 non-null  object
 4   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Nome do Município                                      129308 non-null  object
 5   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Código da Escola                                       129308 non-null  object
 6   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Nome da Escola                                         129308 non-null  object
 7   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Localização                                            129308 non-null  object
 8   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Dependência Administrativa                             129308 non-null  object
 9   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 10  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 11  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 12  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 13  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 14  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 15  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 16  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 17  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 18  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 19  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 20  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   129309 non-null  object
 21  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Médio                       129309 non-null  object
 22  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Médio                       129309 non-null  object
 23  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Médio                       129309 non-null  object
 24  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Médio                       129309 non-null  object
 25  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Médio                       129309 non-null  object
 26  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Aprovação - Ensino Médio                       129309 non-null  object
 27  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 28  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 29  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 30  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 31  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 32  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 33  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 34  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 35  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 36  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 37  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 38  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  129309 non-null  object
 39  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Médio                      129309 non-null  object
 40  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Médio                      129309 non-null  object
 41  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Médio                      129309 non-null  object
 42  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Médio                      129309 non-null  object
 43  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Médio                      129309 non-null  object
 44  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Reprovação - Ensino Médio                      129309 non-null  object
 45  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 46  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 47  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 48  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 49  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 50  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 51  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 52  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 53  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 54  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 55  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 56  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    129309 non-null  object
 57  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Médio                        129309 non-null  object
 58  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Médio                        129309 non-null  object
 59  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Médio                        129309 non-null  object
 60  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Médio                        129309 non-null  object
 61  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Médio                        129309 non-null  object
 62  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2022 - Taxa de Abandono - Ensino Médio                        129309 non-null  object
dtypes: object(63)
memory usage: 62.2+ MB

In [ ]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
84888,2022,Maricá,33053910,CE ELISIARIO MATTA,Estadual,76.1,9.5,14.4
84891,2022,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,89.2,8.9,1.9
84893,2022,Maricá,33053995,CE PROFESSORA CACILDA SILVA,Estadual,99.2,0.8,0.0
84904,2022,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,74.5,14.8,10.7
84905,2022,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,86.6,13.0,0.4
...,...,...,...,...,...,...,...,...
89590,2022,São Gonçalo,33103968,CIEP 439 LUIZ GONZAGA JUNIOR GONZAGUINHA,Estadual,78.7,13.7,7.6
89597,2022,São Gonçalo,33104182,CIEP BRIZOLAO 409 PROFESSORA ALAIDE DE FIGUERE...,Estadual,72.1,13.4,14.5
89612,2022,São Gonçalo,33114366,CE MARIO TAMBORINDEGUY,Estadual,70.7,18.7,10.6
89815,2022,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,95.3,3.9,0.8
89817,2022,São Gonçalo,33518238,CIEP 513 GEORGE SAVALLA GOMES PALHACO CAREQUINHA,Estadual,73.1,12.5,14.4

In [ ]:
df_final.to_csv('Rendimento2022ano.csv', index=False)

#ANO 2021

In [ ]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('tx_rend_escolas_2021.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Nome do Município","Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Nome da Escola"
85729,Maricá,CEM JOANA BENEDICTA RANGEL
85730,Maricá,CE ELISIARIO MATTA
85731,Maricá,ESCOLA MUNICIPALIZADA BARRA DE ZACARIAS
85732,Maricá,E M BENVINDO TAQUES HORTA
85733,Maricá,CE DOMICIO DA GAMA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130133 entries, 7 to 130139
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                              Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                              --------------   -----
 0   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Ano                                                    130131 non-null  object
 1   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Região                                                 130130 non-null  object
 2   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - UF                                                     130130 non-null  object
 3   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Código do Município                                    130130 non-null  object
 4   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Nome do Município                                      130130 non-null  object
 5   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Código da Escola                                       130130 non-null  object
 6   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Nome da Escola                                         130130 non-null  object
 7   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Localização                                            130130 non-null  object
 8   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Dependência Administrativa                             130130 non-null  object
 9   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 10  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 11  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 12  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 13  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 14  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 15  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 16  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 17  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 18  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 19  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 20  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   130131 non-null  object
 21  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Médio                       130131 non-null  object
 22  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Médio                       130131 non-null  object
 23  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Médio                       130131 non-null  object
 24  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Médio                       130131 non-null  object
 25  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Médio                       130131 non-null  object
 26  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Aprovação - Ensino Médio                       130131 non-null  object
 27  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 28  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 29  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 30  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 31  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 32  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 33  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 34  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 35  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 36  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 37  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 38  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  130131 non-null  object
 39  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Médio                      130131 non-null  object
 40  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Médio                      130131 non-null  object
 41  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Médio                      130131 non-null  object
 42  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Médio                      130131 non-null  object
 43  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Médio                      130131 non-null  object
 44  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Reprovação - Ensino Médio                      130131 non-null  object
 45  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 46  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 47  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 48  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 49  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 50  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 51  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 52  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 53  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 54  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 55  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 56  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    130131 non-null  object
 57  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Médio                        130131 non-null  object
 58  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Médio                        130131 non-null  object
 59  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Médio                        130131 non-null  object
 60  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Médio                        130131 non-null  object
 61  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Médio                        130131 non-null  object
 62  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2021 - Taxa de Abandono - Ensino Médio                        130131 non-null  object
dtypes: object(63)
memory usage: 62.5+ MB

In [ ]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
85730,2021,Maricá,33053910,CE ELISIARIO MATTA,Estadual,88.4,9.9,1.7
85733,2021,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,90.6,8.6,0.8
85735,2021,Maricá,33053995,CE PROFESSORA CACILDA SILVA,Estadual,87.6,11.8,0.6
85746,2021,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,94.2,2.3,3.5
85747,2021,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,83.7,15.6,0.7
...,...,...,...,...,...,...,...,...
90414,2021,São Gonçalo,33103968,CIEP 439 LUIZ GONZAGA JUNIOR GONZAGUINHA,Estadual,95.3,1.2,3.5
90421,2021,São Gonçalo,33104182,CIEP BRIZOLAO 409 PROFESSORA ALAIDE DE FIGUERE...,Estadual,94.3,5.7,0.0
90437,2021,São Gonçalo,33114366,CE MARIO TAMBORINDEGUY,Estadual,93.1,6.9,0.0
90628,2021,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,99.4,0.6,0.0
90630,2021,São Gonçalo,33518238,CIEP 513 GEORGE SAVALLA GOMES PALHACO CAREQUINHA,Estadual,79.2,5.0,15.8

In [ ]:
df_final.to_csv('Rendimento2021ano.csv', index=False)

#ANO 2020

In [ ]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('tx_rend_escolas_2020.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Nome do Município","Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Nome da Escola"
86783,Maricá,CEM JOANA BENEDICTA RANGEL
86784,Maricá,CE ELISIARIO MATTA
86785,Maricá,ESCOLA MUNICIPALIZADA BARRA DE ZACARIAS
86786,Maricá,E M BENVINDO TAQUES HORTA
86787,Maricá,CE DOMICIO DA GAMA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131233 entries, 7 to 131239
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                              Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                              --------------   -----
 0   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Ano                                                    131231 non-null  object
 1   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Região                                                 131230 non-null  object
 2   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - UF                                                     131230 non-null  object
 3   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Código do Município                                    131230 non-null  object
 4   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Nome do Município                                      131230 non-null  object
 5   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Código da Escola                                       131230 non-null  object
 6   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Nome da Escola                                         131230 non-null  object
 7   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Localização                                            131230 non-null  object
 8   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Dependência Administrativa                             131230 non-null  object
 9   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 10  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 11  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 12  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 13  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 14  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 15  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 16  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 17  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 18  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 19  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 20  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   131231 non-null  object
 21  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Médio                       131231 non-null  object
 22  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Médio                       131231 non-null  object
 23  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Médio                       131231 non-null  object
 24  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Médio                       131231 non-null  object
 25  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Médio                       131231 non-null  object
 26  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Aprovação - Ensino Médio                       131231 non-null  object
 27  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 28  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 29  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 30  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 31  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 32  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 33  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 34  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 35  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 36  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 37  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 38  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  131231 non-null  object
 39  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Médio                      131231 non-null  object
 40  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Médio                      131231 non-null  object
 41  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Médio                      131231 non-null  object
 42  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Médio                      131231 non-null  object
 43  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Médio                      131231 non-null  object
 44  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Reprovação - Ensino Médio                      131231 non-null  object
 45  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 46  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 47  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 48  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 49  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 50  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 51  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 52  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 53  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 54  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 55  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 56  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    131231 non-null  object
 57  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Médio                        131231 non-null  object
 58  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Médio                        131231 non-null  object
 59  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Médio                        131231 non-null  object
 60  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Médio                        131231 non-null  object
 61  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Médio                        131231 non-null  object
 62  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2020 - Taxa de Abandono - Ensino Médio                        131231 non-null  object
dtypes: object(63)
memory usage: 63.1+ MB

In [ ]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
86784,2020,Maricá,33053910,CE ELISIARIO MATTA,Estadual,95.2,4.8,0.0
86787,2020,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,97.8,2.2,0.0
86789,2020,Maricá,33053995,CE PROFESSORA CACILDA SILVA,Estadual,100.0,0.0,0.0
86800,2020,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,97.3,2.7,0.0
86801,2020,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,96.4,3.6,0.0
...,...,...,...,...,...,...,...,...
91462,2020,São Gonçalo,33103968,CIEP 439 LUIZ GONZAGA JUNIOR GONZAGUINHA,Estadual,100.0,0.0,0.0
91470,2020,São Gonçalo,33104182,CIEP BRIZOLAO 409 PROFESSORA ALAIDE DE FIGUERE...,Estadual,65.3,34.7,0.0
91486,2020,São Gonçalo,33114366,CE MARIO TAMBORINDEGUY,Estadual,95.2,4.8,0.0
91679,2020,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,100.0,0.0,0.0
91681,2020,São Gonçalo,33518238,CIEP 513 GEORGE SAVALLA GOMES PALHACO CAREQUINHA,Estadual,89.6,10.4,0.0

In [ ]:
df_final.to_csv('Rendimento2020ano.csv', index=False)

#ANO 2019

In [ ]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('tx_rend_escolas_2019.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Nome do Município","Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Nome da Escola"
87863,Maricá,CEM JOANA BENEDICTA RANGEL
87864,Maricá,COLEGIO CENECISTA MARICA
87865,Maricá,CE ELISIARIO MATTA
87866,Maricá,ESCOLA MUNICIPALIZADA BARRA DE ZACARIAS
87867,Maricá,E M BENVINDO TAQUES HORTA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132462 entries, 7 to 132468
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                              Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                              --------------   -----
 0   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Ano                                                    132460 non-null  object
 1   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Região                                                 132459 non-null  object
 2   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - UF                                                     132459 non-null  object
 3   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Código do Município                                    132459 non-null  object
 4   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Nome do Município                                      132459 non-null  object
 5   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Código da Escola                                       132459 non-null  object
 6   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Nome da Escola                                         132459 non-null  object
 7   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Localização                                            132459 non-null  object
 8   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Dependência Administrativa                             132459 non-null  object
 9   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 10  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 11  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 12  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 13  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 14  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 15  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 16  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 17  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 18  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 19  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 20  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   132460 non-null  object
 21  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Médio                       132460 non-null  object
 22  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Médio                       132460 non-null  object
 23  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Médio                       132460 non-null  object
 24  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Médio                       132460 non-null  object
 25  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Médio                       132460 non-null  object
 26  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Aprovação - Ensino Médio                       132460 non-null  object
 27  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 28  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 29  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 30  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 31  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 32  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 33  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 34  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 35  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 36  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 37  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 38  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  132460 non-null  object
 39  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Médio                      132460 non-null  object
 40  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Médio                      132460 non-null  object
 41  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Médio                      132460 non-null  object
 42  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Médio                      132460 non-null  object
 43  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Médio                      132460 non-null  object
 44  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Reprovação - Ensino Médio                      132460 non-null  object
 45  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 46  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 47  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 48  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 49  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 50  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 51  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 52  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 53  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 54  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 55  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 56  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    132460 non-null  object
 57  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Médio                        132460 non-null  object
 58  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Médio                        132460 non-null  object
 59  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Médio                        132460 non-null  object
 60  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Médio                        132460 non-null  object
 61  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Médio                        132460 non-null  object
 62  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2019 - Taxa de Abandono - Ensino Médio                        132460 non-null  object
dtypes: object(63)
memory usage: 63.7+ MB

In [ ]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
87865,2019,Maricá,33053910,CE ELISIARIO MATTA,Estadual,82.4,10.7,6.9
87868,2019,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,83.6,15.6,0.8
87870,2019,Maricá,33053995,CE PROFESSORA CACILDA SILVA,Estadual,85.0,8.6,6.4
87881,2019,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,66.3,25.2,8.5
87882,2019,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,84.4,14.6,1.0
...,...,...,...,...,...,...,...,...
92570,2019,São Gonçalo,33103968,CIEP 439 LUIZ GONZAGA JUNIOR GONZAGUINHA,Estadual,88.2,11.8,0.0
92579,2019,São Gonçalo,33104182,CIEP 409 ALAIDE DE FIGUEREDO SANTOS,Estadual,74.2,17.6,8.2
92596,2019,São Gonçalo,33114366,CE MARIO TAMBORINDEGUY,Estadual,80.8,16.7,2.5
92790,2019,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,94.7,5.0,0.3
92792,2019,São Gonçalo,33518238,CIEP 513 GEORGE SAVALLA GOMES PALHACO CAREQUINHA,Estadual,70.1,15.5,14.4

In [ ]:
df_final.to_csv('Rendimento2019ano.csv', index=False)

#ANO 2018

In [1]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('TX_REND_ESCOLAS_2018.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Nome do Município","Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Nome da Escola"
89786,Maricá,CEM JOANA BENEDICTA RANGEL
89787,Maricá,COLEGIO CENECISTA MARICA
89788,Maricá,CE ELISIARIO MATTA
89789,Maricá,ESCOLA MUNICIPALIZADA BARRA DE ZACARIAS
89790,Maricá,E M BENVINDO TAQUES HORTA

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134461 entries, 7 to 134467
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                              Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                              --------------   -----
 0   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Ano                                                    134459 non-null  object
 1   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Região                                                 134458 non-null  object
 2   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - UF                                                     134458 non-null  object
 3   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Código do Município                                    134458 non-null  object
 4   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Nome do Município                                      134458 non-null  object
 5   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Código da Escola                                       134458 non-null  object
 6   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Nome da Escola                                         134458 non-null  object
 7   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Localização                                            134458 non-null  object
 8   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Dependência Administrativa                             134458 non-null  object
 9   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 10  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 11  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 12  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 13  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 14  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 15  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 16  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 17  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 18  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 19  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 20  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   134459 non-null  object
 21  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Médio                       134459 non-null  object
 22  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Médio                       134459 non-null  object
 23  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Médio                       134459 non-null  object
 24  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Médio                       134459 non-null  object
 25  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Médio                       134459 non-null  object
 26  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Aprovação - Ensino Médio                       134459 non-null  object
 27  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 28  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 29  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 30  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 31  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 32  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 33  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 34  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 35  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 36  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 37  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 38  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  134459 non-null  object
 39  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Médio                      134459 non-null  object
 40  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Médio                      134459 non-null  object
 41  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Médio                      134459 non-null  object
 42  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Médio                      134459 non-null  object
 43  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Médio                      134459 non-null  object
 44  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Reprovação - Ensino Médio                      134459 non-null  object
 45  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 46  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 47  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 48  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 49  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 50  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 51  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 52  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 53  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 54  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 55  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 56  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    134459 non-null  object
 57  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Médio                        134459 non-null  object
 58  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Médio                        134459 non-null  object
 59  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Médio                        134459 non-null  object
 60  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Médio                        134459 non-null  object
 61  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Médio                        134459 non-null  object
 62  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2018 - Taxa de Abandono - Ensino Médio                        134459 non-null  object
dtypes: object(63)
memory usage: 64.6+ MB

In [3]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
89788,2018,Maricá,33053910,CE ELISIARIO MATTA,Estadual,86.4,11.1,2.5
89791,2018,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,87.7,9.9,2.4
89793,2018,Maricá,33053995,CE PROFESSORA CACILDA SILVA,Estadual,75.7,16.5,7.8
89804,2018,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,75.2,17.5,7.3
89805,2018,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,87.7,11.1,1.2
...,...,...,...,...,...,...,...,...
94485,2018,São Gonçalo,33103968,CIEP BRIZOLAO 439 LUIZ GONZAGA JUNIOR - GONZAG...,Estadual,87.9,7.6,4.5
94494,2018,São Gonçalo,33104182,CIEP 409 ALAIDE DE FIGUEREDO SANTOS,Estadual,69.4,28.9,1.7
94512,2018,São Gonçalo,33114366,CE MARIO TAMBORINDEGUY,Estadual,84.3,15.7,0.0
94700,2018,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,89.5,10.5,0.0
94702,2018,São Gonçalo,33518238,CIEP 513 GEORGE SAVALLA GOMES - PALHACO CAREQU...,Estadual,66.4,16.4,17.2

In [5]:
df_final.to_csv('Rendimento2018ano.csv', index=False)

#ANO 2017

In [10]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('TX_REND_ESCOLAS_2017.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Nome do Município","Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Nome da Escola"
92447,Maricá,CEM JOANA BENEDICTA RANGEL
92448,Maricá,COLEGIO CENECISTA MARICA
92449,Maricá,CE ELISIARIO MATTA
92450,Maricá,ESCOLA MUNICIPALIZADA BARRA DE ZACARIAS
92451,Maricá,E M BENVINDO TAQUES HORTA

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137303 entries, 7 to 137309
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                              Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                              --------------   -----
 0   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Ano                                                    137301 non-null  object
 1   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Região                                                 137300 non-null  object
 2   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - UF                                                     137300 non-null  object
 3   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Código do Município                                    137300 non-null  object
 4   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Nome do Município                                      137300 non-null  object
 5   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Código da Escola                                       137300 non-null  object
 6   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Nome da Escola                                         137300 non-null  object
 7   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Localização                                            137300 non-null  object
 8   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Dependência Administrativa                             137300 non-null  object
 9   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 10  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 11  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 12  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 13  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 14  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 15  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 16  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 17  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 18  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 19  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 20  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   137301 non-null  object
 21  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Médio                       137301 non-null  object
 22  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Médio                       137301 non-null  object
 23  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Médio                       137301 non-null  object
 24  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Médio                       137301 non-null  object
 25  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Médio                       137301 non-null  object
 26  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Aprovação - Ensino Médio                       137301 non-null  object
 27  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 28  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 29  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 30  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 31  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 32  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 33  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 34  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 35  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 36  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 37  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 38  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  137301 non-null  object
 39  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Médio                      137301 non-null  object
 40  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Médio                      137301 non-null  object
 41  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Médio                      137301 non-null  object
 42  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Médio                      137301 non-null  object
 43  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Médio                      137301 non-null  object
 44  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Reprovação - Ensino Médio                      137301 non-null  object
 45  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 46  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 47  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 48  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 49  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 50  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 51  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 52  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 53  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 54  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 55  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 56  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    137301 non-null  object
 57  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Médio                        137301 non-null  object
 58  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Médio                        137301 non-null  object
 59  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Médio                        137301 non-null  object
 60  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Médio                        137301 non-null  object
 61  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Médio                        137301 non-null  object
 62  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono) por escola, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental e Médio - Escolas - 2017 - Taxa de Abandono - Ensino Médio                        137301 non-null  object
dtypes: object(63)
memory usage: 66.0+ MB

In [13]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
92449,2017,Maricá,33053910,CE ELISIARIO MATTA,Estadual,87.7,9.0,3.3
92452,2017,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,91.5,7.8,0.7
92454,2017,Maricá,33053995,CE PROFESSORA CACILDA SILVA,Estadual,76.7,20.0,3.3
92465,2017,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,72.3,24.1,3.6
92466,2017,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,84.7,12.2,3.1
...,...,...,...,...,...,...,...,...
97139,2017,São Gonçalo,33103968,CIEP 439 LUIZ GONZAGA JUNIOR - GONZAGUINHA,Estadual,85.1,14.9,0.0
97148,2017,São Gonçalo,33104182,CIEP 409 ALAIDE DE FIGUEREDO SANTOS,Estadual,67.7,27.5,4.8
97166,2017,São Gonçalo,33114366,CE MARIO TAMBORINDEGUY,Estadual,71.3,22.3,6.4
97350,2017,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,99.4,0.6,0.0
97352,2017,São Gonçalo,33518238,CIEP 513 GEORGE SAVALLA GOMES - PALHACO CAREQU...,Estadual,74.8,15.8,9.4

In [14]:
df_final.to_csv('Rendimento2017ano.csv', index=False)

#ANO 2016

In [15]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('TX_REND_ESCOLAS_2016.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Nome do Município","Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Nome da Escola"
94751,Maricá,CEM JOANA BENEDICTA RANGEL
94752,Maricá,COLEGIO CENECISTA MARICA
94753,Maricá,CE ELISIARIO MATTA
94754,Maricá,ESCOLA MUNICIPALIZADA BARRA DE ZACARIAS
94755,Maricá,E M BENVINDO TAQUES HORTA

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139818 entries, 7 to 139824
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                                                          Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                                                          --------------   -----
 0   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Ano                                                    139816 non-null  object
 1   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Região                                                 139815 non-null  object
 2   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - UF                                                     139815 non-null  object
 3   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Código do Município                                    139815 non-null  object
 4   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Nome do Município                                      139815 non-null  object
 5   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Código da Escola                                       139815 non-null  object
 6   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Nome da Escola                                         139815 non-null  object
 7   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Localização                                            139815 non-null  object
 8   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Dependência Administrativa                             139815 non-null  object
 9   Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 10  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 11  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 12  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 13  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 14  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 15  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 16  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 17  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 18  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 19  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 20  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos   139816 non-null  object
 21  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Médio                       139816 non-null  object
 22  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Médio                       139816 non-null  object
 23  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Médio                       139816 non-null  object
 24  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Médio                       139816 non-null  object
 25  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Médio                       139816 non-null  object
 26  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Aprovação - Ensino Médio                       139816 non-null  object
 27  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 28  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 29  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 30  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 31  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 32  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 33  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 34  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 35  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 36  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 37  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 38  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  139816 non-null  object
 39  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Médio                      139816 non-null  object
 40  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Médio                      139816 non-null  object
 41  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Médio                      139816 non-null  object
 42  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Médio                      139816 non-null  object
 43  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Médio                      139816 non-null  object
 44  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Reprovação - Ensino Médio                      139816 non-null  object
 45  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 46  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 47  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 48  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 49  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 50  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 51  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 52  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 53  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 54  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 55  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 56  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos    139816 non-null  object
 57  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Médio                        139816 non-null  object
 58  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Médio                        139816 non-null  object
 59  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Médio                        139816 non-null  object
 60  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Médio                        139816 non-null  object
 61  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Médio                        139816 non-null  object
 62  Taxas de Rendimento Escolar (Aprovação, Reprovação e Abandono), segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, divididos por série, por escola em 2016. - Taxa de Abandono - Ensino Médio                        139816 non-null  object
dtypes: object(63)
memory usage: 67.2+ MB

In [17]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola', # <-- Nova coluna para o seu JOIN futuro!
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
94753,2016,Maricá,33053910,CE ELISIARIO MATTA,Estadual,81.8,7.8,10.4
94756,2016,Maricá,33053952,CE DOMICIO DA GAMA,Estadual,75.7,11.1,13.2
94770,2016,Maricá,33054177,CE DOUTOR JOAO GOMES DE MATTOS SOBRINHO,Estadual,78.0,9.3,12.7
94771,2016,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,89.1,9.7,1.2
94773,2016,Maricá,33054215,CE EUCLYDES PAULO DA SILVA,Estadual,63.8,11.2,25.0
...,...,...,...,...,...,...,...,...
99453,2016,São Gonçalo,33103968,CIEP BRIZOLAO 439 LUIZ GONZAGA JUNIOR - GONZAG...,Estadual,77.1,22.9,0.0
99461,2016,São Gonçalo,33104182,CIEP 409 ALAIDE DE FIGUEREDO SANTOS,Estadual,79.7,5.4,14.9
99479,2016,São Gonçalo,33114366,CE MARIO TAMBORINDEGUY,Estadual,61.9,24.7,13.4
99654,2016,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,99.1,0.9,0.0
99656,2016,São Gonçalo,33518238,CIEP 513 GEORGE SAVALLA GOMES - PALHACO CAREQU...,Estadual,64.2,17.6,18.2

In [18]:
df_final.to_csv('Rendimento2016ano.csv', index = False)

#ANO 2015

In [20]:
import pandas as pd
# 1. Carrega o arquivo inteiro sem cabeçalho
df_raw = pd.read_excel('TX_REND_ESCOLAS_2015.xlsx', sheet_name='ESCOLAS', header=None)

# 2. O Segredo: Isolar apenas as linhas do Excel que contêm os subtítulos úteis (índices 4, 5 e 6).
# O .ffill(axis=1) preenche as células mescladas para a direita para não perdermos nenhuma informação.
cabecalho = df_raw.iloc[4:7].ffill(axis=1).fillna('')

# 3. Cria nomes de colunas limpos juntando essas três linhas
nomes_colunas = []
for col in cabecalho.columns:
    partes = []
    for val in cabecalho[col]:
        texto = str(val).strip()
        # Junta os textos ignorando células vazias e repetições
        if texto and (not partes or partes[-1] != texto):
            partes.append(texto)
    # O resultado será algo como: "Taxa de Aprovação - Ensino Médio - Total"
    nomes_colunas.append(' - '.join(partes))

# 4. Aplica os nomes criados ao DataFrame e corta os dados (que começam na linha 8 / índice 7)
df = df_raw.iloc[7:].copy()
df.columns = nomes_colunas

# 5. Filtra pelos municípios desejados
col_mun = [c for c in df.columns if 'Nome do Município' in c][0]
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']
df_filtrado = df[df[col_mun].isin(municipios_alvo)].copy()

# 6. Seleciona as colunas de ID e as de Taxa do Ensino Médio (Aprovação, Reprovação, Abandono)
colunas_id = [c for c in df.columns if 'Nome do Município' in c or 'Nome da Escola' in c]

colunas_taxas = [c for c in df.columns if
                 'Ensino Médio' in c and
                 'Total' in c and
                 any(taxa in c for taxa in ['Aprovação', 'Reprovação', 'Abandono'])]

# 7. Tabela final
df_final = df_filtrado[colunas_id + colunas_taxas]
display(df_final.head())

,"Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Nome do Município","Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Nome da Escola"
95696,Maricá,E M PROFESSORA DIRCE MARINHO GOMES
95697,Maricá,COLEGIO EVOLUCAO DE ITAIPUACU LTDA
95698,Maricá,CENTRO EDUCACIONAL VIVENDO E APRENDENDO
95699,Maricá,EM SAO BENTO DA LAGOA
95700,Maricá,CENTRO EDUCACIONAL VIEIRA BRUM

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140872 entries, 7 to 140878
Data columns (total 63 columns):
 #   Column                                                                                                                                                                                                                                               Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                               --------------   -----
 0   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Ano                                                       140870 non-null  object
 1   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Região                                                    140866 non-null  object
 2   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - UF                                                        140866 non-null  object
 3   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Código do Município                                       140866 non-null  object
 4   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Nome do Município                                         140866 non-null  object
 5   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Código da Escola                                          140866 non-null  object
 6   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Nome da Escola                                            140866 non-null  object
 7   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Localização                                               140866 non-null  object
 8   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Dependência Administrativa                                140866 non-null  object
 9   Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 10  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 11  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 12  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 13  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 14  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 15  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 16  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 17  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 18  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 19  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 20  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Fundamental de 8 e 9 anos      140867 non-null  object
 21  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Médio                          140867 non-null  object
 22  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Médio                          140867 non-null  object
 23  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Médio                          140867 non-null  object
 24  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Médio                          140867 non-null  object
 25  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Médio                          140867 non-null  object
 26  Taxa de Aprovação - 2015 - Taxa de Aprovação, segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Aprovação - Ensino Médio                          140867 non-null  object
 27  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 28  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 29  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 30  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 31  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 32  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 33  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 34  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 35  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 36  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 37  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 38  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Fundamental de 8 e 9 anos  140867 non-null  object
 39  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Médio                      140867 non-null  object
 40  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Médio                      140867 non-null  object
 41  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Médio                      140867 non-null  object
 42  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Médio                      140867 non-null  object
 43  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Médio                      140867 non-null  object
 44  Taxa de Reprovação - 2015 - Taxa de Reprovação,  segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Reprovação - Ensino Médio                      140867 non-null  object
 45  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 46  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 47  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 48  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 49  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 50  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 51  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 52  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 53  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 54  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 55  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 56  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Fundamental de 8 e 9 anos       140867 non-null  object
 57  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Médio                           140867 non-null  object
 58  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Médio                           140867 non-null  object
 59  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Médio                           140867 non-null  object
 60  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Médio                           140867 non-null  object
 61  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Médio                           140867 non-null  object
 62  Taxa de Abandono - 2015 - Taxa de Abandono,   segundo a Localização e a Dependência Administrativa, nos Níveis de Ensino Fundamental de 8 e 9 Anos e Médio, por escola e série, em 2015. - Taxa de Abandono - Ensino Médio                           140867 non-null  object
dtypes: object(63)
memory usage: 67.7+ MB

In [22]:
# 1. Puxamos as colunas incluindo o índice 5 (Código da Escola)
indices_alvo = [0, 4, 5, 6, 8, 21, 39, 57]
df_limpo = df.iloc[:, indices_alvo].copy()

# 2. Renomeamos as colunas adicionando o Codigo_Escola no lugar certo
df_limpo.columns = [
    'Ano',
    'Municipio',
    'Codigo_Escola',
    'Escola',
    'Dependencia',
    'Aprovacao_EM_Total',
    'Reprovacao_EM_Total',
    'Abandono_EM_Total'
]

# 3. Aplicamos os filtros (Cidades desejadas + Rede Estadual)
municipios_alvo = ['Niterói', 'São Gonçalo', 'Maricá', 'Rio de Janeiro']

df_estadual = df_limpo[
    (df_limpo['Municipio'].isin(municipios_alvo)) &
    (df_limpo['Dependencia'] == 'Estadual')
].copy()

# 4. Limpeza final dos dados: converte os textos/tracinhos para números e NaN
colunas_taxas = ['Aprovacao_EM_Total', 'Reprovacao_EM_Total', 'Abandono_EM_Total']

for col in colunas_taxas:
    df_estadual[col] = pd.to_numeric(df_estadual[col], errors='coerce')

# Remove escolas estaduais que não tenham nenhum dado preenchido de Ensino Médio
df_final = df_estadual.dropna(subset=colunas_taxas, how='all').copy()

# Exibe a tabela pronta!
display(df_final)

,Ano,Municipio,Codigo_Escola,Escola,Dependencia,Aprovacao_EM_Total,Reprovacao_EM_Total,Abandono_EM_Total
95728,2015,Maricá,33096929,CIEP 391 PROFESSOR ROBSON MENDONCA LOU,Estadual,63.9,23.8,12.3
95736,2015,Maricá,33102414,CIEP 259 PROFESSORA MARIA DO AMPARO RANGEL DE ...,Estadual,86.1,10.8,3.1
95739,2015,Maricá,33054339,CE FRANCISCO JOSE DO NASCIMENTO,Estadual,77.3,14.5,8.2
95753,2015,Maricá,33054215,CE EUCLYDES PAULO DA SILVA,Estadual,72.2,21.7,6.1
95755,2015,Maricá,33054185,CE CAIO FRANCISCO DE FIGUEIREDO,Estadual,86.6,9.1,4.3
...,...,...,...,...,...,...,...,...
100573,2015,São Gonçalo,33089469,CE PROFESSORA ANTONIETA PALMEIRA,Estadual,75.7,24.3,0.0
100574,2015,São Gonçalo,33089396,CE LAURO CORREA,Estadual,56.2,39.1,4.7
100584,2015,São Gonçalo,33507210,CE COMENDADOR VALENTIM DOS SANTOS DINIZ,Estadual,99.3,0.7,0.0
100588,2015,São Gonçalo,33090459,CE PROFESSORA ODYSSEA SILVEIRA DE SIQUEIRA,Estadual,74.1,25.9,0.0
100592,2015,São Gonçalo,33090270,CE AMANDA VELASCO,Estadual,78.5,21.5,0.0

In [23]:
df_final.to_csv('Rendimento2015ano.csv', index=False)